//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BNP_Workflows.GestcomWebService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://xmlns.example.com/1490372061630", ConfigurationName="GestcomWebService.portType")]
    public interface portType {
        
        [System.ServiceModel.OperationContractAttribute(Action="/BNPPRE_RESI_DISPATCHER/Interface/intfwsResiDispatcher-service.serviceagent/intfw" +
            "swsResiDispatcherEndpoint1/wsResiDispatcherOp", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        BNP_Workflows.GestcomWebService.wsResiDispatcherOpResponse wsResiDispatcherOp(BNP_Workflows.GestcomWebService.wsResiDispatcherOpRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="/BNPPRE_RESI_DISPATCHER/Interface/intfwsResiDispatcher-service.serviceagent/intfw" +
            "swsResiDispatcherEndpoint1/wsResiDispatcherOp", ReplyAction="*")]
        System.Threading.Tasks.Task<BNP_Workflows.GestcomWebService.wsResiDispatcherOpResponse> wsResiDispatcherOpAsync(BNP_Workflows.GestcomWebService.wsResiDispatcherOpRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://com.bnpparibas.realestate.model.esb.contract.crm")]
    public partial class Dossier : object, System.ComponentModel.INotifyPropertyChanged {
        
        private contrat contratField;
        
        private TMA[] tMAField;
        
        private commissions commissionsField;
        
        private string parrainField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public contrat contrat {
            get {
                return this.contratField;
            }
            set {
                this.contratField = value;
                this.RaisePropertyChanged("contrat");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("TMA", Order=1)]
        public TMA[] TMA {
            get {
                return this.tMAField;
            }
            set {
                this.tMAField = value;
                this.RaisePropertyChanged("TMA");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public commissions commissions {
            get {
                return this.commissionsField;
            }
            set {
                this.commissionsField = value;
                this.RaisePropertyChanged("commissions");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string parrain {
            get {
                return this.parrainField;
            }
            set {
                this.parrainField = value;
                this.RaisePropertyChanged("parrain");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://com.bnpparibas.realestate.model.esb.contract.crm")]
    public partial class contrat : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string vendeur_nomField;
        
        private string vendeur_prenomField;
        
        private string vendeur_uidField;
        
        private string program_nameField;
        
        private string program_id_wincomField;
        
        private string programm_id_gestcomField;
        
        private string statutField;
        
        private System.DateTime date_visa_back_officeField;
        
        private bool date_visa_back_officeFieldSpecified;
        
        private System.DateTime date_visa_dir_coField;
        
        private bool date_visa_dir_coFieldSpecified;
        
        private System.DateTime date_visa_complianceField;
        
        private bool date_visa_complianceFieldSpecified;
        
        private System.DateTime date_visa_dir_progField;
        
        private bool date_visa_dir_progFieldSpecified;
        
        private System.DateTime date_visa_relation_acqField;
        
        private bool date_visa_relation_acqFieldSpecified;
        
        private string objectiveField;
        
        private bool concerne_client_bnpField;
        
        private string origineField;
        
        private string prescripteurField;
        
        private bool retrocession_bnpField;
        
        private decimal retrocession_montantField;
        
        private bool retrocession_montantFieldSpecified;
        
        private string retrocession_bnp_code_agenceField;
        
        private decimal tma_total_ttcField;
        
        private bool tma_total_ttcFieldSpecified;
        
        private decimal tma_depositField;
        
        private bool tma_depositFieldSpecified;
        
        private decimal tma_shippingField;
        
        private bool tma_shippingFieldSpecified;
        
        private System.DateTime tma_date_depositField;
        
        private bool tma_date_depositFieldSpecified;
        
        private string tma_deposit_bankField;
        
        private string tma_deposit_numberField;
        
        private decimal price_gridField;
        
        private decimal price_tva_rateField;
        
        private decimal price_post_tvaField;
        
        private bool price_post_tvaFieldSpecified;
        
        private decimal adv_max_rateField;
        
        private decimal adv_max_amountField;
        
        private decimal adv_price_reductionField;
        
        private decimal adv_notary_feeField;
        
        private decimal adv_tmaField;
        
        private decimal adv_funding_appealField;
        
        private decimal adv_otherField;
        
        private string adv_other_commentsField;
        
        private decimal adv_total_1Field;
        
        private decimal adv_total_2Field;
        
        private decimal adv_rateField;
        
        private bool adv_rateFieldSpecified;
        
        private decimal final_priceField;
        
        private bool no_funding_requireField;
        
        private bool no_funding_requireFieldSpecified;
        
        private string other_funding_methodField;
        
        private string other_funding_commentsField;
        
        private decimal security_deposit_amountField;
        
        private bool security_deposit_amountFieldSpecified;
        
        private string security_deposit_typeField;
        
        private string security_deposit_numberField;
        
        private string security_deposit_notaryField;
        
        private string lignageField;
        
        private System.DateTime date_prereservationField;
        
        private bool date_prereservationFieldSpecified;
        
        private System.DateTime dateoptionField;
        
        private bool dateoptionFieldSpecified;
        
        private acquereur acquereurField;
        
        private lot lotField;
        
        private emprunt empruntField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Vendeur_nom {
            get {
                return this.vendeur_nomField;
            }
            set {
                this.vendeur_nomField = value;
                this.RaisePropertyChanged("Vendeur_nom");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Vendeur_prenom {
            get {
                return this.vendeur_prenomField;
            }
            set {
                this.vendeur_prenomField = value;
                this.RaisePropertyChanged("Vendeur_prenom");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Vendeur_uid {
            get {
                return this.vendeur_uidField;
            }
            set {
                this.vendeur_uidField = value;
                this.RaisePropertyChanged("Vendeur_uid");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Program_name {
            get {
                return this.program_nameField;
            }
            set {
                this.program_nameField = value;
                this.RaisePropertyChanged("Program_name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Program_id_wincom {
            get {
                return this.program_id_wincomField;
            }
            set {
                this.program_id_wincomField = value;
                this.RaisePropertyChanged("Program_id_wincom");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Programm_id_gestcom {
            get {
                return this.programm_id_gestcomField;
            }
            set {
                this.programm_id_gestcomField = value;
                this.RaisePropertyChanged("Programm_id_gestcom");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string statut {
            get {
                return this.statutField;
            }
            set {
                this.statutField = value;
                this.RaisePropertyChanged("statut");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public System.DateTime Date_visa_back_office {
            get {
                return this.date_visa_back_officeField;
            }
            set {
                this.date_visa_back_officeField = value;
                this.RaisePropertyChanged("Date_visa_back_office");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Date_visa_back_officeSpecified {
            get {
                return this.date_visa_back_officeFieldSpecified;
            }
            set {
                this.date_visa_back_officeFieldSpecified = value;
                this.RaisePropertyChanged("Date_visa_back_officeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public System.DateTime Date_visa_dir_co {
            get {
                return this.date_visa_dir_coField;
            }
            set {
                this.date_visa_dir_coField = value;
                this.RaisePropertyChanged("Date_visa_dir_co");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Date_visa_dir_coSpecified {
            get {
                return this.date_visa_dir_coFieldSpecified;
            }
            set {
                this.date_visa_dir_coFieldSpecified = value;
                this.RaisePropertyChanged("Date_visa_dir_coSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public System.DateTime Date_visa_compliance {
            get {
                return this.date_visa_complianceField;
            }
            set {
                this.date_visa_complianceField = value;
                this.RaisePropertyChanged("Date_visa_compliance");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Date_visa_complianceSpecified {
            get {
                return this.date_visa_complianceFieldSpecified;
            }
            set {
                this.date_visa_complianceFieldSpecified = value;
                this.RaisePropertyChanged("Date_visa_complianceSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public System.DateTime Date_visa_dir_prog {
            get {
                return this.date_visa_dir_progField;
            }
            set {
                this.date_visa_dir_progField = value;
                this.RaisePropertyChanged("Date_visa_dir_prog");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Date_visa_dir_progSpecified {
            get {
                return this.date_visa_dir_progFieldSpecified;
            }
            set {
                this.date_visa_dir_progFieldSpecified = value;
                this.RaisePropertyChanged("Date_visa_dir_progSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public System.DateTime Date_visa_relation_acq {
            get {
                return this.date_visa_relation_acqField;
            }
            set {
                this.date_visa_relation_acqField = value;
                this.RaisePropertyChanged("Date_visa_relation_acq");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Date_visa_relation_acqSpecified {
            get {
                return this.date_visa_relation_acqFieldSpecified;
            }
            set {
                this.date_visa_relation_acqFieldSpecified = value;
                this.RaisePropertyChanged("Date_visa_relation_acqSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string Objective {
            get {
                return this.objectiveField;
            }
            set {
                this.objectiveField = value;
                this.RaisePropertyChanged("Objective");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public bool Concerne_client_bnp {
            get {
                return this.concerne_client_bnpField;
            }
            set {
                this.concerne_client_bnpField = value;
                this.RaisePropertyChanged("Concerne_client_bnp");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string Origine {
            get {
                return this.origineField;
            }
            set {
                this.origineField = value;
                this.RaisePropertyChanged("Origine");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public string Prescripteur {
            get {
                return this.prescripteurField;
            }
            set {
                this.prescripteurField = value;
                this.RaisePropertyChanged("Prescripteur");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public bool Retrocession_bnp {
            get {
                return this.retrocession_bnpField;
            }
            set {
                this.retrocession_bnpField = value;
                this.RaisePropertyChanged("Retrocession_bnp");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public decimal Retrocession_montant {
            get {
                return this.retrocession_montantField;
            }
            set {
                this.retrocession_montantField = value;
                this.RaisePropertyChanged("Retrocession_montant");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Retrocession_montantSpecified {
            get {
                return this.retrocession_montantFieldSpecified;
            }
            set {
                this.retrocession_montantFieldSpecified = value;
                this.RaisePropertyChanged("Retrocession_montantSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public string Retrocession_bnp_code_agence {
            get {
                return this.retrocession_bnp_code_agenceField;
            }
            set {
                this.retrocession_bnp_code_agenceField = value;
                this.RaisePropertyChanged("Retrocession_bnp_code_agence");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        public decimal tma_total_ttc {
            get {
                return this.tma_total_ttcField;
            }
            set {
                this.tma_total_ttcField = value;
                this.RaisePropertyChanged("tma_total_ttc");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool tma_total_ttcSpecified {
            get {
                return this.tma_total_ttcFieldSpecified;
            }
            set {
                this.tma_total_ttcFieldSpecified = value;
                this.RaisePropertyChanged("tma_total_ttcSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=20)]
        public decimal tma_deposit {
            get {
                return this.tma_depositField;
            }
            set {
                this.tma_depositField = value;
                this.RaisePropertyChanged("tma_deposit");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool tma_depositSpecified {
            get {
                return this.tma_depositFieldSpecified;
            }
            set {
                this.tma_depositFieldSpecified = value;
                this.RaisePropertyChanged("tma_depositSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=21)]
        public decimal tma_shipping {
            get {
                return this.tma_shippingField;
            }
            set {
                this.tma_shippingField = value;
                this.RaisePropertyChanged("tma_shipping");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool tma_shippingSpecified {
            get {
                return this.tma_shippingFieldSpecified;
            }
            set {
                this.tma_shippingFieldSpecified = value;
                this.RaisePropertyChanged("tma_shippingSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=22)]
        public System.DateTime tma_date_deposit {
            get {
                return this.tma_date_depositField;
            }
            set {
                this.tma_date_depositField = value;
                this.RaisePropertyChanged("tma_date_deposit");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool tma_date_depositSpecified {
            get {
                return this.tma_date_depositFieldSpecified;
            }
            set {
                this.tma_date_depositFieldSpecified = value;
                this.RaisePropertyChanged("tma_date_depositSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=23)]
        public string tma_deposit_bank {
            get {
                return this.tma_deposit_bankField;
            }
            set {
                this.tma_deposit_bankField = value;
                this.RaisePropertyChanged("tma_deposit_bank");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=24)]
        public string tma_deposit_number {
            get {
                return this.tma_deposit_numberField;
            }
            set {
                this.tma_deposit_numberField = value;
                this.RaisePropertyChanged("tma_deposit_number");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=25)]
        public decimal price_grid {
            get {
                return this.price_gridField;
            }
            set {
                this.price_gridField = value;
                this.RaisePropertyChanged("price_grid");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=26)]
        public decimal price_tva_rate {
            get {
                return this.price_tva_rateField;
            }
            set {
                this.price_tva_rateField = value;
                this.RaisePropertyChanged("price_tva_rate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=27)]
        public decimal price_post_tva {
            get {
                return this.price_post_tvaField;
            }
            set {
                this.price_post_tvaField = value;
                this.RaisePropertyChanged("price_post_tva");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool price_post_tvaSpecified {
            get {
                return this.price_post_tvaFieldSpecified;
            }
            set {
                this.price_post_tvaFieldSpecified = value;
                this.RaisePropertyChanged("price_post_tvaSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=28)]
        public decimal adv_max_rate {
            get {
                return this.adv_max_rateField;
            }
            set {
                this.adv_max_rateField = value;
                this.RaisePropertyChanged("adv_max_rate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=29)]
        public decimal adv_max_amount {
            get {
                return this.adv_max_amountField;
            }
            set {
                this.adv_max_amountField = value;
                this.RaisePropertyChanged("adv_max_amount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=30)]
        public decimal adv_price_reduction {
            get {
                return this.adv_price_reductionField;
            }
            set {
                this.adv_price_reductionField = value;
                this.RaisePropertyChanged("adv_price_reduction");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=31)]
        public decimal adv_notary_fee {
            get {
                return this.adv_notary_feeField;
            }
            set {
                this.adv_notary_feeField = value;
                this.RaisePropertyChanged("adv_notary_fee");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=32)]
        public decimal adv_tma {
            get {
                return this.adv_tmaField;
            }
            set {
                this.adv_tmaField = value;
                this.RaisePropertyChanged("adv_tma");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=33)]
        public decimal adv_funding_appeal {
            get {
                return this.adv_funding_appealField;
            }
            set {
                this.adv_funding_appealField = value;
                this.RaisePropertyChanged("adv_funding_appeal");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=34)]
        public decimal adv_other {
            get {
                return this.adv_otherField;
            }
            set {
                this.adv_otherField = value;
                this.RaisePropertyChanged("adv_other");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=35)]
        public string adv_other_comments {
            get {
                return this.adv_other_commentsField;
            }
            set {
                this.adv_other_commentsField = value;
                this.RaisePropertyChanged("adv_other_comments");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=36)]
        public decimal adv_total_1 {
            get {
                return this.adv_total_1Field;
            }
            set {
                this.adv_total_1Field = value;
                this.RaisePropertyChanged("adv_total_1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=37)]
        public decimal adv_total_2 {
            get {
                return this.adv_total_2Field;
            }
            set {
                this.adv_total_2Field = value;
                this.RaisePropertyChanged("adv_total_2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=38)]
        public decimal adv_rate {
            get {
                return this.adv_rateField;
            }
            set {
                this.adv_rateField = value;
                this.RaisePropertyChanged("adv_rate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool adv_rateSpecified {
            get {
                return this.adv_rateFieldSpecified;
            }
            set {
                this.adv_rateFieldSpecified = value;
                this.RaisePropertyChanged("adv_rateSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=39)]
        public decimal final_price {
            get {
                return this.final_priceField;
            }
            set {
                this.final_priceField = value;
                this.RaisePropertyChanged("final_price");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=40)]
        public bool no_funding_require {
            get {
                return this.no_funding_requireField;
            }
            set {
                this.no_funding_requireField = value;
                this.RaisePropertyChanged("no_funding_require");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool no_funding_requireSpecified {
            get {
                return this.no_funding_requireFieldSpecified;
            }
            set {
                this.no_funding_requireFieldSpecified = value;
                this.RaisePropertyChanged("no_funding_requireSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=41)]
        public string other_funding_method {
            get {
                return this.other_funding_methodField;
            }
            set {
                this.other_funding_methodField = value;
                this.RaisePropertyChanged("other_funding_method");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=42)]
        public string other_funding_comments {
            get {
                return this.other_funding_commentsField;
            }
            set {
                this.other_funding_commentsField = value;
                this.RaisePropertyChanged("other_funding_comments");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=43)]
        public decimal security_deposit_amount {
            get {
                return this.security_deposit_amountField;
            }
            set {
                this.security_deposit_amountField = value;
                this.RaisePropertyChanged("security_deposit_amount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool security_deposit_amountSpecified {
            get {
                return this.security_deposit_amountFieldSpecified;
            }
            set {
                this.security_deposit_amountFieldSpecified = value;
                this.RaisePropertyChanged("security_deposit_amountSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=44)]
        public string security_deposit_type {
            get {
                return this.security_deposit_typeField;
            }
            set {
                this.security_deposit_typeField = value;
                this.RaisePropertyChanged("security_deposit_type");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=45)]
        public string security_deposit_number {
            get {
                return this.security_deposit_numberField;
            }
            set {
                this.security_deposit_numberField = value;
                this.RaisePropertyChanged("security_deposit_number");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=46)]
        public string security_deposit_notary {
            get {
                return this.security_deposit_notaryField;
            }
            set {
                this.security_deposit_notaryField = value;
                this.RaisePropertyChanged("security_deposit_notary");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=47)]
        public string Lignage {
            get {
                return this.lignageField;
            }
            set {
                this.lignageField = value;
                this.RaisePropertyChanged("Lignage");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=48)]
        public System.DateTime date_prereservation {
            get {
                return this.date_prereservationField;
            }
            set {
                this.date_prereservationField = value;
                this.RaisePropertyChanged("date_prereservation");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool date_prereservationSpecified {
            get {
                return this.date_prereservationFieldSpecified;
            }
            set {
                this.date_prereservationFieldSpecified = value;
                this.RaisePropertyChanged("date_prereservationSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=49)]
        public System.DateTime dateoption {
            get {
                return this.dateoptionField;
            }
            set {
                this.dateoptionField = value;
                this.RaisePropertyChanged("dateoption");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dateoptionSpecified {
            get {
                return this.dateoptionFieldSpecified;
            }
            set {
                this.dateoptionFieldSpecified = value;
                this.RaisePropertyChanged("dateoptionSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=50)]
        public acquereur acquereur {
            get {
                return this.acquereurField;
            }
            set {
                this.acquereurField = value;
                this.RaisePropertyChanged("acquereur");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=51)]
        public lot lot {
            get {
                return this.lotField;
            }
            set {
                this.lotField = value;
                this.RaisePropertyChanged("lot");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=52)]
        public emprunt emprunt {
            get {
                return this.empruntField;
            }
            set {
                this.empruntField = value;
                this.RaisePropertyChanged("emprunt");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://com.bnpparibas.realestate.model.esb.contract.crm")]
    public partial class acquereur : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string civilityField;
        
        private string firstnameField;
        
        private string lastnameField;
        
        private string emailField;
        
        private string mobilephoneField;
        
        private string prophoneField;
        
        private string homephoneField;
        
        private string address1Field;
        
        private string address2Field;
        
        private string address3Field;
        
        private string zip_codeField;
        
        private string cityField;
        
        private string countryField;
        
        private bool has_retiredField;
        
        private bool has_retiredFieldSpecified;
        
        private System.DateTime retirement_dateField;
        
        private bool retirement_dateFieldSpecified;
        
        private string family_statusField;
        
        private System.DateTime birthdayField;
        
        private bool birthdayFieldSpecified;
        
        private string birthplaceField;
        
        private string nationalityField;
        
        private string professionField;
        
        private string employer_addressField;
        
        private string employer_nameField;
        
        private decimal annual_incomeField;
        
        private bool annual_incomeFieldSpecified;
        
        private string date_annual_incomeField;
        
        private string number_of_childrenField;
        
        private string credential_typeField;
        
        private string credential_numberField;
        
        private System.DateTime credential_validity_endField;
        
        private bool credential_validity_endFieldSpecified;
        
        private string current_houseField;
        
        private decimal current_rentField;
        
        private bool current_rentFieldSpecified;
        
        private decimal personnal_contribution_amountField;
        
        private bool personnal_contribution_amountFieldSpecified;
        
        private string personnal_contribution_origineField;
        
        private decimal financing_needField;
        
        private bool financing_needFieldSpecified;
        
        private decimal current_loan_initialField;
        
        private bool current_loan_initialFieldSpecified;
        
        private decimal current_loan_monthly_paymentField;
        
        private bool current_loan_monthly_paymentFieldSpecified;
        
        private decimal current_loan_outstanding_capitalField;
        
        private bool current_loan_outstanding_capitalFieldSpecified;
        
        private bool bridge_loanField;
        
        private bool bridge_loanFieldSpecified;
        
        private decimal owner_shareField;
        
        private bool owner_shareFieldSpecified;
        
        private System.DateTime signing_dateField;
        
        private bool signing_dateFieldSpecified;
        
        private string signing_locationField;
        
        private enfant enfantField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Civility {
            get {
                return this.civilityField;
            }
            set {
                this.civilityField = value;
                this.RaisePropertyChanged("Civility");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Firstname {
            get {
                return this.firstnameField;
            }
            set {
                this.firstnameField = value;
                this.RaisePropertyChanged("Firstname");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Lastname {
            get {
                return this.lastnameField;
            }
            set {
                this.lastnameField = value;
                this.RaisePropertyChanged("Lastname");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
                this.RaisePropertyChanged("Email");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Mobilephone {
            get {
                return this.mobilephoneField;
            }
            set {
                this.mobilephoneField = value;
                this.RaisePropertyChanged("Mobilephone");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Prophone {
            get {
                return this.prophoneField;
            }
            set {
                this.prophoneField = value;
                this.RaisePropertyChanged("Prophone");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string Homephone {
            get {
                return this.homephoneField;
            }
            set {
                this.homephoneField = value;
                this.RaisePropertyChanged("Homephone");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string address1 {
            get {
                return this.address1Field;
            }
            set {
                this.address1Field = value;
                this.RaisePropertyChanged("address1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string address2 {
            get {
                return this.address2Field;
            }
            set {
                this.address2Field = value;
                this.RaisePropertyChanged("address2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string address3 {
            get {
                return this.address3Field;
            }
            set {
                this.address3Field = value;
                this.RaisePropertyChanged("address3");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string zip_code {
            get {
                return this.zip_codeField;
            }
            set {
                this.zip_codeField = value;
                this.RaisePropertyChanged("zip_code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string City {
            get {
                return this.cityField;
            }
            set {
                this.cityField = value;
                this.RaisePropertyChanged("City");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string Country {
            get {
                return this.countryField;
            }
            set {
                this.countryField = value;
                this.RaisePropertyChanged("Country");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public bool has_retired {
            get {
                return this.has_retiredField;
            }
            set {
                this.has_retiredField = value;
                this.RaisePropertyChanged("has_retired");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool has_retiredSpecified {
            get {
                return this.has_retiredFieldSpecified;
            }
            set {
                this.has_retiredFieldSpecified = value;
                this.RaisePropertyChanged("has_retiredSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=14)]
        public System.DateTime retirement_date {
            get {
                return this.retirement_dateField;
            }
            set {
                this.retirement_dateField = value;
                this.RaisePropertyChanged("retirement_date");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool retirement_dateSpecified {
            get {
                return this.retirement_dateFieldSpecified;
            }
            set {
                this.retirement_dateFieldSpecified = value;
                this.RaisePropertyChanged("retirement_dateSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public string family_status {
            get {
                return this.family_statusField;
            }
            set {
                this.family_statusField = value;
                this.RaisePropertyChanged("family_status");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=16)]
        public System.DateTime Birthday {
            get {
                return this.birthdayField;
            }
            set {
                this.birthdayField = value;
                this.RaisePropertyChanged("Birthday");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool BirthdaySpecified {
            get {
                return this.birthdayFieldSpecified;
            }
            set {
                this.birthdayFieldSpecified = value;
                this.RaisePropertyChanged("BirthdaySpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public string Birthplace {
            get {
                return this.birthplaceField;
            }
            set {
                this.birthplaceField = value;
                this.RaisePropertyChanged("Birthplace");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public string Nationality {
            get {
                return this.nationalityField;
            }
            set {
                this.nationalityField = value;
                this.RaisePropertyChanged("Nationality");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        public string Profession {
            get {
                return this.professionField;
            }
            set {
                this.professionField = value;
                this.RaisePropertyChanged("Profession");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=20)]
        public string employer_address {
            get {
                return this.employer_addressField;
            }
            set {
                this.employer_addressField = value;
                this.RaisePropertyChanged("employer_address");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=21)]
        public string employer_name {
            get {
                return this.employer_nameField;
            }
            set {
                this.employer_nameField = value;
                this.RaisePropertyChanged("employer_name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=22)]
        public decimal annual_income {
            get {
                return this.annual_incomeField;
            }
            set {
                this.annual_incomeField = value;
                this.RaisePropertyChanged("annual_income");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool annual_incomeSpecified {
            get {
                return this.annual_incomeFieldSpecified;
            }
            set {
                this.annual_incomeFieldSpecified = value;
                this.RaisePropertyChanged("annual_incomeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=23)]
        public string date_annual_income {
            get {
                return this.date_annual_incomeField;
            }
            set {
                this.date_annual_incomeField = value;
                this.RaisePropertyChanged("date_annual_income");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", Order=24)]
        public string Number_of_children {
            get {
                return this.number_of_childrenField;
            }
            set {
                this.number_of_childrenField = value;
                this.RaisePropertyChanged("Number_of_children");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=25)]
        public string credential_type {
            get {
                return this.credential_typeField;
            }
            set {
                this.credential_typeField = value;
                this.RaisePropertyChanged("credential_type");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=26)]
        public string credential_number {
            get {
                return this.credential_numberField;
            }
            set {
                this.credential_numberField = value;
                this.RaisePropertyChanged("credential_number");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=27)]
        public System.DateTime credential_validity_end {
            get {
                return this.credential_validity_endField;
            }
            set {
                this.credential_validity_endField = value;
                this.RaisePropertyChanged("credential_validity_end");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool credential_validity_endSpecified {
            get {
                return this.credential_validity_endFieldSpecified;
            }
            set {
                this.credential_validity_endFieldSpecified = value;
                this.RaisePropertyChanged("credential_validity_endSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=28)]
        public string current_house {
            get {
                return this.current_houseField;
            }
            set {
                this.current_houseField = value;
                this.RaisePropertyChanged("current_house");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=29)]
        public decimal current_rent {
            get {
                return this.current_rentField;
            }
            set {
                this.current_rentField = value;
                this.RaisePropertyChanged("current_rent");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool current_rentSpecified {
            get {
                return this.current_rentFieldSpecified;
            }
            set {
                this.current_rentFieldSpecified = value;
                this.RaisePropertyChanged("current_rentSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=30)]
        public decimal personnal_contribution_amount {
            get {
                return this.personnal_contribution_amountField;
            }
            set {
                this.personnal_contribution_amountField = value;
                this.RaisePropertyChanged("personnal_contribution_amount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool personnal_contribution_amountSpecified {
            get {
                return this.personnal_contribution_amountFieldSpecified;
            }
            set {
                this.personnal_contribution_amountFieldSpecified = value;
                this.RaisePropertyChanged("personnal_contribution_amountSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=31)]
        public string personnal_contribution_origine {
            get {
                return this.personnal_contribution_origineField;
            }
            set {
                this.personnal_contribution_origineField = value;
                this.RaisePropertyChanged("personnal_contribution_origine");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=32)]
        public decimal financing_need {
            get {
                return this.financing_needField;
            }
            set {
                this.financing_needField = value;
                this.RaisePropertyChanged("financing_need");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool financing_needSpecified {
            get {
                return this.financing_needFieldSpecified;
            }
            set {
                this.financing_needFieldSpecified = value;
                this.RaisePropertyChanged("financing_needSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=33)]
        public decimal current_loan_initial {
            get {
                return this.current_loan_initialField;
            }
            set {
                this.current_loan_initialField = value;
                this.RaisePropertyChanged("current_loan_initial");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool current_loan_initialSpecified {
            get {
                return this.current_loan_initialFieldSpecified;
            }
            set {
                this.current_loan_initialFieldSpecified = value;
                this.RaisePropertyChanged("current_loan_initialSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=34)]
        public decimal current_loan_monthly_payment {
            get {
                return this.current_loan_monthly_paymentField;
            }
            set {
                this.current_loan_monthly_paymentField = value;
                this.RaisePropertyChanged("current_loan_monthly_payment");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool current_loan_monthly_paymentSpecified {
            get {
                return this.current_loan_monthly_paymentFieldSpecified;
            }
            set {
                this.current_loan_monthly_paymentFieldSpecified = value;
                this.RaisePropertyChanged("current_loan_monthly_paymentSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=35)]
        public decimal current_loan_outstanding_capital {
            get {
                return this.current_loan_outstanding_capitalField;
            }
            set {
                this.current_loan_outstanding_capitalField = value;
                this.RaisePropertyChanged("current_loan_outstanding_capital");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool current_loan_outstanding_capitalSpecified {
            get {
                return this.current_loan_outstanding_capitalFieldSpecified;
            }
            set {
                this.current_loan_outstanding_capitalFieldSpecified = value;
                this.RaisePropertyChanged("current_loan_outstanding_capitalSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=36)]
        public bool bridge_loan {
            get {
                return this.bridge_loanField;
            }
            set {
                this.bridge_loanField = value;
                this.RaisePropertyChanged("bridge_loan");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool bridge_loanSpecified {
            get {
                return this.bridge_loanFieldSpecified;
            }
            set {
                this.bridge_loanFieldSpecified = value;
                this.RaisePropertyChanged("bridge_loanSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=37)]
        public decimal owner_share {
            get {
                return this.owner_shareField;
            }
            set {
                this.owner_shareField = value;
                this.RaisePropertyChanged("owner_share");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool owner_shareSpecified {
            get {
                return this.owner_shareFieldSpecified;
            }
            set {
                this.owner_shareFieldSpecified = value;
                this.RaisePropertyChanged("owner_shareSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=38)]
        public System.DateTime signing_date {
            get {
                return this.signing_dateField;
            }
            set {
                this.signing_dateField = value;
                this.RaisePropertyChanged("signing_date");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool signing_dateSpecified {
            get {
                return this.signing_dateFieldSpecified;
            }
            set {
                this.signing_dateFieldSpecified = value;
                this.RaisePropertyChanged("signing_dateSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=39)]
        public string signing_location {
            get {
                return this.signing_locationField;
            }
            set {
                this.signing_locationField = value;
                this.RaisePropertyChanged("signing_location");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=40)]
        public enfant enfant {
            get {
                return this.enfantField;
            }
            set {
                this.enfantField = value;
                this.RaisePropertyChanged("enfant");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://com.bnpparibas.realestate.model.esb.contract.crm")]
    public partial class enfant : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.DateTime birthdateField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=0)]
        public System.DateTime Birthdate {
            get {
                return this.birthdateField;
            }
            set {
                this.birthdateField = value;
                this.RaisePropertyChanged("Birthdate");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://com.bnpparibas.realestate.model.esb.contract.crm")]
    public partial class lot : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string typeField;
        
        private string room_numberField;
        
        private string identification_codeField;
        
        private string living_areaField;
        
        private string floorField;
        
        private string stare_nameField;
        
        private string building_nameField;
        
        private decimal price_gridField;
        
        private decimal tva_used_rateField;
        
        private decimal price_post_tvaField;
        
        private bool price_post_tvaFieldSpecified;
        
        private decimal adv_used_rateField;
        
        private decimal adv_amountField;
        
        private bool adv_amountFieldSpecified;
        
        private decimal adv_used_amountField;
        
        private decimal price_contractField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
                this.RaisePropertyChanged("Type");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", Order=1)]
        public string room_number {
            get {
                return this.room_numberField;
            }
            set {
                this.room_numberField = value;
                this.RaisePropertyChanged("room_number");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string identification_code {
            get {
                return this.identification_codeField;
            }
            set {
                this.identification_codeField = value;
                this.RaisePropertyChanged("identification_code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", Order=3)]
        public string living_area {
            get {
                return this.living_areaField;
            }
            set {
                this.living_areaField = value;
                this.RaisePropertyChanged("living_area");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", Order=4)]
        public string Floor {
            get {
                return this.floorField;
            }
            set {
                this.floorField = value;
                this.RaisePropertyChanged("Floor");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string stare_name {
            get {
                return this.stare_nameField;
            }
            set {
                this.stare_nameField = value;
                this.RaisePropertyChanged("stare_name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string building_name {
            get {
                return this.building_nameField;
            }
            set {
                this.building_nameField = value;
                this.RaisePropertyChanged("building_name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public decimal price_grid {
            get {
                return this.price_gridField;
            }
            set {
                this.price_gridField = value;
                this.RaisePropertyChanged("price_grid");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public decimal tva_used_rate {
            get {
                return this.tva_used_rateField;
            }
            set {
                this.tva_used_rateField = value;
                this.RaisePropertyChanged("tva_used_rate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public decimal price_post_tva {
            get {
                return this.price_post_tvaField;
            }
            set {
                this.price_post_tvaField = value;
                this.RaisePropertyChanged("price_post_tva");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool price_post_tvaSpecified {
            get {
                return this.price_post_tvaFieldSpecified;
            }
            set {
                this.price_post_tvaFieldSpecified = value;
                this.RaisePropertyChanged("price_post_tvaSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public decimal adv_used_rate {
            get {
                return this.adv_used_rateField;
            }
            set {
                this.adv_used_rateField = value;
                this.RaisePropertyChanged("adv_used_rate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public decimal adv_amount {
            get {
                return this.adv_amountField;
            }
            set {
                this.adv_amountField = value;
                this.RaisePropertyChanged("adv_amount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool adv_amountSpecified {
            get {
                return this.adv_amountFieldSpecified;
            }
            set {
                this.adv_amountFieldSpecified = value;
                this.RaisePropertyChanged("adv_amountSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public decimal adv_used_amount {
            get {
                return this.adv_used_amountField;
            }
            set {
                this.adv_used_amountField = value;
                this.RaisePropertyChanged("adv_used_amount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public decimal price_contract {
            get {
                return this.price_contractField;
            }
            set {
                this.price_contractField = value;
                this.RaisePropertyChanged("price_contract");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://com.bnpparibas.realestate.model.esb.contract.crm")]
    public partial class emprunt : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string bank_designationField;
        
        private decimal max_rateField;
        
        private bool max_rateFieldSpecified;
        
        private decimal min_amountField;
        
        private bool min_amountFieldSpecified;
        
        private string min_durationField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string bank_designation {
            get {
                return this.bank_designationField;
            }
            set {
                this.bank_designationField = value;
                this.RaisePropertyChanged("bank_designation");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public decimal max_rate {
            get {
                return this.max_rateField;
            }
            set {
                this.max_rateField = value;
                this.RaisePropertyChanged("max_rate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool max_rateSpecified {
            get {
                return this.max_rateFieldSpecified;
            }
            set {
                this.max_rateFieldSpecified = value;
                this.RaisePropertyChanged("max_rateSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public decimal min_amount {
            get {
                return this.min_amountField;
            }
            set {
                this.min_amountField = value;
                this.RaisePropertyChanged("min_amount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool min_amountSpecified {
            get {
                return this.min_amountFieldSpecified;
            }
            set {
                this.min_amountFieldSpecified = value;
                this.RaisePropertyChanged("min_amountSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", Order=3)]
        public string min_duration {
            get {
                return this.min_durationField;
            }
            set {
                this.min_durationField = value;
                this.RaisePropertyChanged("min_duration");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://com.bnpparibas.realestate.model.esb.contract.crm")]
    public partial class TMA : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string ref_optionField;
        
        private string designationField;
        
        private decimal cost_ttcField;
        
        private bool cost_ttcFieldSpecified;
        
        private string is_offeredField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string ref_option {
            get {
                return this.ref_optionField;
            }
            set {
                this.ref_optionField = value;
                this.RaisePropertyChanged("ref_option");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Designation {
            get {
                return this.designationField;
            }
            set {
                this.designationField = value;
                this.RaisePropertyChanged("Designation");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public decimal cost_ttc {
            get {
                return this.cost_ttcField;
            }
            set {
                this.cost_ttcField = value;
                this.RaisePropertyChanged("cost_ttc");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool cost_ttcSpecified {
            get {
                return this.cost_ttcFieldSpecified;
            }
            set {
                this.cost_ttcFieldSpecified = value;
                this.RaisePropertyChanged("cost_ttcSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", Order=3)]
        public string is_offered {
            get {
                return this.is_offeredField;
            }
            set {
                this.is_offeredField = value;
                this.RaisePropertyChanged("is_offered");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://com.bnpparibas.realestate.model.esb.contract.crm")]
    public partial class commissions : object, System.ComponentModel.INotifyPropertyChanged {
        
        private decimal commission_rateField;
        
        private decimal commission_amountField;
        
        private beneficiaire beneficiaireField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public decimal commission_rate {
            get {
                return this.commission_rateField;
            }
            set {
                this.commission_rateField = value;
                this.RaisePropertyChanged("commission_rate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public decimal commission_amount {
            get {
                return this.commission_amountField;
            }
            set {
                this.commission_amountField = value;
                this.RaisePropertyChanged("commission_amount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public beneficiaire beneficiaire {
            get {
                return this.beneficiaireField;
            }
            set {
                this.beneficiaireField = value;
                this.RaisePropertyChanged("beneficiaire");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://com.bnpparibas.realestate.model.esb.contract.crm")]
    public partial class beneficiaire : object, System.ComponentModel.INotifyPropertyChanged {
        
        private decimal shareField;
        
        private decimal total_commissionField;
        
        private decimal bonusField;
        
        private decimal booking_amountField;
        
        private decimal act_amountField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public decimal Share {
            get {
                return this.shareField;
            }
            set {
                this.shareField = value;
                this.RaisePropertyChanged("Share");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public decimal total_commission {
            get {
                return this.total_commissionField;
            }
            set {
                this.total_commissionField = value;
                this.RaisePropertyChanged("total_commission");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public decimal Bonus {
            get {
                return this.bonusField;
            }
            set {
                this.bonusField = value;
                this.RaisePropertyChanged("Bonus");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public decimal booking_amount {
            get {
                return this.booking_amountField;
            }
            set {
                this.booking_amountField = value;
                this.RaisePropertyChanged("booking_amount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public decimal act_amount {
            get {
                return this.act_amountField;
            }
            set {
                this.act_amountField = value;
                this.RaisePropertyChanged("act_amount");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Request", WrapperNamespace="http://com.bnpparibas.realestate.interfaces.contract", IsWrapped=true)]
    public partial class wsResiDispatcherOpRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://com.bnpparibas.realestate.model.esb.contract.crm", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://com.bnpparibas.realestate.model.esb.contract.crm")]
        public BNP_Workflows.GestcomWebService.Dossier Dossier;
        
        public wsResiDispatcherOpRequest() {
        }
        
        public wsResiDispatcherOpRequest(BNP_Workflows.GestcomWebService.Dossier Dossier) {
            this.Dossier = Dossier;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Response", WrapperNamespace="http://com.bnpparibas.realestate.interfaces.contract", IsWrapped=true)]
    public partial class wsResiDispatcherOpResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://com.bnpparibas.realestate.interfaces.contract", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string returnCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://com.bnpparibas.realestate.interfaces.contract", Order=1)]
        public string returnMessage;
        
        public wsResiDispatcherOpResponse() {
        }
        
        public wsResiDispatcherOpResponse(string returnCode, string returnMessage) {
            this.returnCode = returnCode;
            this.returnMessage = returnMessage;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface portTypeChannel : BNP_Workflows.GestcomWebService.portType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class portTypeClient : System.ServiceModel.ClientBase<BNP_Workflows.GestcomWebService.portType>, BNP_Workflows.GestcomWebService.portType {
        
        public portTypeClient() {
        }
        
        public portTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public portTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public portTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public portTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BNP_Workflows.GestcomWebService.wsResiDispatcherOpResponse BNP_Workflows.GestcomWebService.portType.wsResiDispatcherOp(BNP_Workflows.GestcomWebService.wsResiDispatcherOpRequest request) {
            return base.Channel.wsResiDispatcherOp(request);
        }
        
        public string wsResiDispatcherOp(BNP_Workflows.GestcomWebService.Dossier Dossier, out string returnMessage) {
            BNP_Workflows.GestcomWebService.wsResiDispatcherOpRequest inValue = new BNP_Workflows.GestcomWebService.wsResiDispatcherOpRequest();
            inValue.Dossier = Dossier;
            BNP_Workflows.GestcomWebService.wsResiDispatcherOpResponse retVal = ((BNP_Workflows.GestcomWebService.portType)(this)).wsResiDispatcherOp(inValue);
            returnMessage = retVal.returnMessage;
            return retVal.returnCode;
        }
        
        public System.Threading.Tasks.Task<BNP_Workflows.GestcomWebService.wsResiDispatcherOpResponse> wsResiDispatcherOpAsync(BNP_Workflows.GestcomWebService.wsResiDispatcherOpRequest request) {
            return base.Channel.wsResiDispatcherOpAsync(request);
        }
    }
}
